name: Build SystemMonitor

on:
  push:
    tags:
      - 'v*'   # runs when you push a version tag like v1.0
  workflow_dispatch:  # allows manual trigger

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller psutil matplotlib numpy pillow paramiko cryptography fpdf2

      - name: Build with PyInstaller
        run: |
          if [[ "${{ runner.os }}" == "Linux" ]]; then
            pyinstaller build_linux.spec
          elif [[ "${{ runner.os }}" == "Windows" ]]; then
            pyinstaller build_windows.spec
          else
            pyinstaller build_macos.spec
          fi


      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SystemMonitor-${{ matrix.os }}
          path: dist/
