name: Build & Package

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: python dependency_installer.py
        shell: bash

      - name: Build on Linux
        if: runner.os == 'Linux'
        run: |
          # Build binary
          pyinstaller --noconfirm --clean --onefile --name SystemMonitor main.py
          # Create .deb package
          mkdir -p dist/deb
          sudo apt-get update && sudo apt-get install -y ruby ruby-dev build-essential
          sudo gem install --no-document fpm
          fpm -s dir -t deb -n systemmonitor -v 1.0 dist/SystemMonitor=/usr/bin/SystemMonitor
          # Zip the binary and .deb
          zip -r dist/systemmonitor-linux.zip dist/SystemMonitor dist/systemmonitor_1.0_amd64.deb
        shell: bash

      - name: Build on macOS
        if: runner.os == 'macOS'
        run: |
          # Build .app bundle
          pyinstaller --noconfirm --clean --windowed --name SystemMonitor main.py
          # Create .dmg installer
          hdiutil create -volname "SystemMonitor" -srcfolder dist/SystemMonitor.app -ov -format UDZO dist/SystemMonitor.dmg
          # Zip the .app and .dmg
          zip -r dist/systemmonitor-macos.zip dist/SystemMonitor.app dist/SystemMonitor.dmg
        shell: bash

      - name: Build on Windows
        if: runner.os == 'Windows'
        run: |
          pyinstaller --noconfirm --clean --onefile --windowed --name SystemMonitor.exe main.py
          # Zip the .exe
          powershell Compress-Archive -Path dist\SystemMonitor.exe -DestinationPath dist\systemmonitor-windows.zip
        shell: pwsh

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ runner.os }}
          path: dist/*
