name: Build and Package SystemMonitor

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install psutil matplotlib numpy paramiko GPUtil fpdf

      - name: Build with PyInstaller
        run: |
          if [ "${{ runner.os }}" != "Windows" ]; then
            pyinstaller --noconfirm --clean --onefile --windowed main.py
          else
            pyinstaller --noconfirm --clean --onefile --windowed main.py
        shell: bash

      # macOS DMG
      - name: Package macOS .dmg
        if: runner.os == 'macOS'
        run: |
          hdiutil create -volname "SystemMonitor" \
            -srcfolder "dist/SystemMonitor(macOS)" \
            -ov -format UDZO "dist/SystemMonitor-macOS.dmg"

      # Windows ZIP
      - name: Package Windows .zip
        if: runner.os == 'Windows'
        run: |
          Compress-Archive -Path dist\main.exe -DestinationPath dist\SystemMonitor-Windows.zip
        shell: pwsh

      # Linux .deb
      - name: Package Linux .deb
        if: runner.os == 'Linux'
        run: |
          mkdir -p package/DEBIAN
          echo "Package: systemmonitor" > package/DEBIAN/control
          echo "Version: 1.0.0" >> package/DEBIAN/control
          echo "Section: utils" >> package/DEBIAN/control
          echo "Priority: optional" >> package/DEBIAN/control
          echo "Architecture: amd64" >> package/DEBIAN/control
          echo "Maintainer: Your Name <you@example.com>" >> package/DEBIAN/control
          echo "Description: System Monitor App" >> package/DEBIAN/control
          mkdir -p package/usr/local/bin
          cp dist/main package/usr/local/bin/SystemMonitor
          dpkg-deb --build package dist/SystemMonitor-1.0.0.deb

      # Upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SystemMonitor-${{ runner.os }}
          path: |
            dist/*.dmg
            dist/*.zip
            dist/*.deb
